### ISSUE TITLE
Broken link to CoP in ReadMe

### ISSUE THREAD

**Issue by Candice-Louw** [WorldHealthOrganization/godata#119]
### Bug description
The link to the Go.Data Community is not working - a 403 Error page is shown.

### To Reproduce
1. Go to https://github.com/WorldHealthOrganization/godata?tab=readme-ov-file#how-can-i-contribute
2. Click on https://community-godata.who.int/
3. Error page appears

### Expected behavior
No error page should appear.  Not clear if the link is incorrect on GitHub, or if the web page is down.  Suspecting that the correct link to the CoP would be https://goarn.who.int/virtual-spaces/godataproject.

### Screenshots
![image](https://github.com/user-attachments/assets/6331d5ee-b838-4a59-8853-f5bbbc6025c7)

### Desktop (please complete the following information):
 - Browser: Chrome

**Comment by silviaemorreale** [comment]
Dear [Candice-Louw](https://github.com/Candice-Louw),

Many thanks for reporting this bug. We have updated the link to the Go.Data CoP so that it is now functional. 

Kind regards,
Silvia on behalf of the Go.Data project team
