### ISSUE TITLE
R Shiny - add documentation on hosting options for reference app example

### ISSUE THREAD

**Issue by sarahollis** [WorldHealthOrganization/godata#42]

**Comment by sarahollis** [comment]
assistance with setting up Go.Data reference shiny app on WHO Shiny Server (token available) and documentation for deploying in your own setting.
https://github.com/WorldHealthOrganization/godata/tree/master/analytics/r-reporting/r-shiny

**Comment by silviaemorreale** [comment]
Documentations shared
