### ISSUE TITLE
Lab - Technical Documentation for Go.Data Users peforming lab-related analyses or operations

### ISSUE THREAD

**Issue by sarahollis** [WorldHealthOrganization/godata#47]
Build out Laboratory page (location to be decided, within overall hierarchy)

- [ ] Technical Overview of Go.Data Lab Module Variables
- [ ] Key Considerations for Lab Module use (incl config of reference data, bulk actions with API of laboratories, etc).
- [ ] How to import Go.Data lab data (incl sample lab import template)
- [ ] How to Export Go.Data lab data (incl sample dummy data export with lab vars)
- [ ] How to Produce analyses with Go.Data lab Data (incl sample use case such as linking to shiny app)

@giovfer

**Comment by silviaemorreale** [comment]
A Laboratory module was created as part of the Go.Data course "Everything you need to know about Go.Data", the module addresses key aspects of the laboratory data management and includes a technical overview of the Lab module variables, key considerations for lab use, how to inport and export lab data.

https://goarnlms.org/group/89/module/73/answer/71

In addition to this, Module 8 on Data visualization covers key aspects on how to produce analyses with Go.Data lab data

 https://goarnlms.org/group/91
