### ISSUE TITLE
Anonymization - add UPC app / documentation

### ISSUE THREAD

**Issue by sarahollis** [WorldHealthOrganization/godata#48]
- [ ] write snippet of project
- [ ] visual diagram of data flow
- [ ] link to repo, and fork to WHO repository: https://github.com/eetac/InSSIDE
- [ ] post on CoP incl PPT (https://docs.google.com/presentation/d/1mwDKdGJflHdh2XhvEHG_RAJdyU0Cdf2n938C-KlZ5Qs/edit?usp=sharing)

**Comment by silviaemorreale** [comment]
Proposal was submitted to be pick up in a different phase.
