### ISSUE TITLE
Select and Apply Open Source License for Go.Data

### ISSUE THREAD

**Issue by smbuthia** [WorldHealthOrganization/godata#75]
Go.Data is an outbreak investigation tool for data collection during health emergencies. It includes use case functionality for case investigation, contact follow-up, visualization of chains of transmission and is designed for flexibility in the field.

Go.Data is the initiative of a group of public health partners and is managed by the Global Outbreak and Response Network coordinated by WHO.

Go.Data aims to strengthen and enhance technical support to all countries for readiness activities; outbreak risk assessments; field investigations and response, including response research.

Go.Data uses various open source software components and modules with various open source licenses including:

- MIT
- GNU AGPL v3.0
- Apache-2.0
- WTFPL
- BSD-2-Clause
- 0BSD
- ISC

We would like to select and apply an appropriate open source license that will take into account the existing open source components.

**Comment by smbuthia** [comment]
GPL v3 license selected. 

Next steps:

- [ ] update README to include copyright and license notice
- [ ] add copyright notice in each file
- [ ] add license notice in each file

**Comment by AlexandreBonneau** [comment]
Another step would be to release the source code as well if it's open-source?
Here perhaps?
