### ISSUE TITLE
Publish Go.Data Public Product Roadmap

### ISSUE THREAD

**Issue by smbuthia** [WorldHealthOrganization/godata#77]
A high level visual that maps out the vision, direction, and evolution of Go.Data over time is an instrumental part of open sourcing Go.Data. Providing the open source community high level details about ongoing work, upcoming features, and issues already resolved empowers them to better plan around their adoption of the software, offer present or future contributions, and manage expectations all around. This also reduces the risk of independent contributors maintaining forks or parallel solutions.

Go.Data's product roadmap is managed internally. This issue proposes making high level product roadmap that is available to the Go.Data open source community. This could be in the form of a GitHub project board with high level descriptions.

**Comment by silviaemorreale** [comment]
Here is a summary of the current Go.Data roadmap. 

Building upon the previous strategies, the strategy for 2024-2026 focus on enhancing and re-activating the Go.Data CoP and ensuring the sustainable development and maintenance of the application. The strategy aims to further solidify Go.Data's role as a vital tool in global public health intelligence for timely and effective responses to infectious disease outbreaks. The key components include:

- Sustaining Go.Data operations through comprehensive maintenance and global technical support.
- Enhancing Go.Data capabilities to address emergency outbreak responses and large-scale deployments.
- Fostering innovation through active engagement with the open-source developer community.
- Promote ownership of Go.Data by revitalizing the Go.Data community of practice and enhancing engagement with
- GOARN partners through improved collaboration, knowledge sharing, and capacity building.
